project_id = "vzwhccciarvirzqmvldl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[db]
enabled = true
port = 54322
major_version = 15

[functions.ai-assistant]
verify_jwt = true

[functions.send-email]
verify_jwt = true