project_id = "vzwhccciarvirzqmvldl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "https://groundpath.com.au"
additional_redirect_urls = ["https://localhost:3000", "https://groundpath.com.au"]
jwt_expiry = 600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true


[db]
enabled = true
port = 54322
major_version = 15

[functions.ai-assistant]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.weekly-newsletter]
verify_jwt = false

[functions.generate-articles]
verify_jwt = false

[functions.check-links]
verify_jwt = false