project_id = "vzwhccciarvirzqmvldl"

[api]
  enabled = true
  extra_search_path = ["public", "extensions"]
  max_rows = 1000
  port = 54321
  schemas = ["public", "graphql_public"]

[auth]
  additional_redirect_urls = ["https://localhost:3000", "https://groundpath.com.au", "https://groundpath.com.au/auth/callback", "https://groundpath.com.au/practitioner/auth/callback", "https://groundpath.com.au/verify-email", "https://groundpath.com.au/practitioner/verify", "https://ground-path.lovable.app", "https://ground-path.lovable.app/auth/callback", "https://ground-path.lovable.app/practitioner/auth/callback", "https://ground-path.lovable.app/verify-email", "https://ground-path.lovable.app/practitioner/verify"]
  enable_signup = true
  enabled = true
  jwt_expiry = 600
  port = 9999
  refresh_token_reuse_interval = 10
  refresh_token_rotation_enabled = true
  site_url = "https://groundpath.com.au"

[db]
  enabled = true
  major_version = 15
  port = 54322

[functions]
  [functions.ai-assistant]
    verify_jwt = true
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-links]
    verify_jwt = false
  [functions.client-ai-assistant]
    verify_jwt = false
  [functions.generate-articles]
    verify_jwt = false
  [functions.send-email]
    verify_jwt = true
  [functions.message-notification]
    verify_jwt = false
  [functions.weekly-newsletter]
    verify_jwt = false
